###
@baseUrl = http://localhost:4455/api

###
post {{baseUrl}}/addStudent
Content-Type: application/json

{
    "name": "Claire",
    "school": "Boston College",
    "hobbies": [
        "hiking",
        "sailing"
    ]
}

###
get {{baseUrl}}/getStudentByName/Claire